### PR TITLE
Cleanup code style

### PR DESCRIPTION
**Pull request by hannesvdvreken**
@neovdr if you want, you can check this cleanup out.

### CODE REVIEW

**Comment by neovdr** [comment]
Will do! I would prefer the 1.1.0 release though so I can move my production composer.jsons away from my fork!

**Comment by hannesvdvreken** [comment]
@neovdr Awaiting the [travis build](https://travis-ci.org/hannesvdvreken/php-oauth/builds/65314075) first and in the meantime trying to reproduce the bug locally.

**Comment by neovdr** [comment]
The campaignMonitor?? I think you need to ensure that the initial call fires within one minute and the return comes at the other minute. For example the call happens at 22:39:57 and completes at 22:40:03. I think that is why the timestamps didn't match

**Comment by hannesvdvreken** [comment]
**edited** you're right. It's just hard to test. Maybe I'll need to inject something that creates the datetime object and always returns the same. The chance that the gap between the first and second DateTime generation is large enough so they don't match is extremely small.

**Comment by hannesvdvreken** [comment]
@neovdr https://github.com/hannesvdvreken/php-oauth/releases/tag/1.1.0
About to board an 8 hour flight, so tagged it anyway for you.

**Comment by neovdr** [comment]
Thanks! You are a saint.

**Pull request merged**
